dist: trusty
language: cpp
if: (branch =~ ^(dev|use_beta|master|test_ci)$) || (tag =~ ^v?[0-9]+\.[0-9]+\.[0-9]+$)
services:
  - docker
matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - TARGET_ARCH=amd64
    - os: osx
      osx_image: xcode9.2
      env:
        - TARGET_ARCH=i386
    - os: linux
      env:
        - TARGET_ARCH=amd64
    - os: linux
      env:
        - TARGET_ARCH=i386
    - os: linux
      env:
        - TARGET_ARCH=arm
    - os: linux
      env:
        - TARGET_ARCH=arm64
    - os: linux
      env:
        - TARGET_ARCH=mips
    - os: linux
      env:
        - TARGET_ARCH=mips64
cache: ccache
addons:
  apt:
    packages:
      - ccache
      - unzip
  homebrew:
    packages:
      - xz
      - unzip
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    rvm install ruby-2.4.0;
    rvm --default use 2.4.0;
    ruby -v;
    brew update;
    fi
install:
  - git submodule init
  - git submodule update
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
    brew install ccache;
    export PATH="/usr/local/opt/ccache/libexec:$PATH";
    fi
script:
  - echo "${TARGET_ARCH}"
  - ./.travis/build.sh
  - if [[ -z $TRAVIS_TAG && $TRAVIS_BRANCH != "use_beta" ]]; then
    ./.travis/test.sh;
    else
    ./.travis/release.sh;
    fi
before_deploy:
  - if [[ -z $TRAVIS_TAG ]]; then
    export TRAVIS_TAG=$(git describe --match "v[0-9]*.[0-9]*.[0-9]*");
    fi
  - export GIT_COMMIT_SHORTCUTS=$(git log --format=%h -1)
  - echo "$TRAVIS_TAG" "$GIT_COMMIT_SHORTCUTS"
deploy:
  - provider: releases
    api_key:
      secure: VHepLaVWIqT52rxdhFDu2Rt+Fy+N1TQCqQGpMgf/L8V38EkFZt+JyMjFpHQUoMNFtj9SIYhtf+MUC7hccGeylW4i0A8ez0fRUiZSyKPrlFjm7hHZifKUjFjApXFqNEnLs9Z1BGWbHNnoTd3sN0CWgf+IZEbxoeKz4aqHJVy1vLUH4o+YgkphEwWqouJ/Vt3xGbqL5pQhbupCk8VqMb3HoiyBTlm4ZVNMYHUgXZ8MwmYNfrruyte1Y5ruz4hBpzNRc1WCWF6gevh4BJJETSfkNFSwVC88xP0Hb6AvlJTeXYwcW6OOSDBavNirWqsCUV6kxylYDPFdkrsmIR1pr/iNkQIKvE8a62POMvgla+0ynAnipm4FuhUgiqJId13cxaErsYj6v6B0lsfAK0JSfi2U4OkqnwbFJj17HMDLmUDH+sr6WD3WRpK7WVaaj4zP+TMfd+d+XO3fZZkb1sSuJ6C9ZlLfIoHX0C8hRQpvboclwr686B2b9B6Wr6TKKeqbLaY++PWmx6I4L5DxVLMBVMYtIA6fcIX6iB/HRg9HEqzzyDDdFauepC5RLjnAt8q4cGx3WaKIbnxoNZKDEkWsUIjKeS2W9kUorlm0bwQz2TVPpT+RqEhJlvPDEYZ3eYosi1TIVrG2WIWv6qu0q3TUxvPrlKeUitDXQ87YJyHauHjtHnY=
    file_glob: true
    file: ${TRAVIS_TAG}/*
    skip_cleanup: true
    overwrite: true
    on:
      tags: true
      repo: richardo2016/fibjs
  - provider: releases
    name: ${TRAVIS_TAG}-beta
    body: Automated release from Travis CI on beta (${TRAVIS_COMMIT})
    prerelease: true
    api_key:
      secure: VHepLaVWIqT52rxdhFDu2Rt+Fy+N1TQCqQGpMgf/L8V38EkFZt+JyMjFpHQUoMNFtj9SIYhtf+MUC7hccGeylW4i0A8ez0fRUiZSyKPrlFjm7hHZifKUjFjApXFqNEnLs9Z1BGWbHNnoTd3sN0CWgf+IZEbxoeKz4aqHJVy1vLUH4o+YgkphEwWqouJ/Vt3xGbqL5pQhbupCk8VqMb3HoiyBTlm4ZVNMYHUgXZ8MwmYNfrruyte1Y5ruz4hBpzNRc1WCWF6gevh4BJJETSfkNFSwVC88xP0Hb6AvlJTeXYwcW6OOSDBavNirWqsCUV6kxylYDPFdkrsmIR1pr/iNkQIKvE8a62POMvgla+0ynAnipm4FuhUgiqJId13cxaErsYj6v6B0lsfAK0JSfi2U4OkqnwbFJj17HMDLmUDH+sr6WD3WRpK7WVaaj4zP+TMfd+d+XO3fZZkb1sSuJ6C9ZlLfIoHX0C8hRQpvboclwr686B2b9B6Wr6TKKeqbLaY++PWmx6I4L5DxVLMBVMYtIA6fcIX6iB/HRg9HEqzzyDDdFauepC5RLjnAt8q4cGx3WaKIbnxoNZKDEkWsUIjKeS2W9kUorlm0bwQz2TVPpT+RqEhJlvPDEYZ3eYosi1TIVrG2WIWv6qu0q3TUxvPrlKeUitDXQ87YJyHauHjtHnY=
    file_glob: true
    file: ${TRAVIS_TAG}/*
    skip_cleanup: true
    overwrite: true
    on:
      branch: use_beta
      repo: richardo2016/fibjs
