/*! @brief tty 流对象, 用于对 tty 进行读取, 写入

 没有途径可以单独创建该类, 全局只有 `require('tty').readStream` 实例

 ```JavaScript
 var tty = require('tty')

 // 从 process.stdin 中读取 1 个字符
 tty.readStream.read(1)
 ```
 */
interface TTYStream : Stream
{
    /*! @brief 查询是否是处于 raw mode, 为 true 时, 表示 tty 被配置为以 raw device 操作时
    */
    readonly Boolean isRaw;

    /*! @brief 恒为 true
    */
    readonly Boolean isTTY;

    /*! @brief 设置 tty 是否以 raw mode 工作
     @param isRawMode 为 true, 表示以 raw mode 工作; 否则以默认模式工作. `readStream.isRaw` 会受该方法设置
     @return 返回自身
     */
    TTYStream setRawMode(Boolean isRawMode);
};
