/*! @brief 基于 binaryen 的非标准的 Wasm 模块, 在基础模块的定义上扩展

  创建方式：
  ```JavaScript
  var wasm = require('wasm');
  
  var wmodule = wasm.parseText('');
  ```
 */
interface WasmModule : Buffer
{
    /*! @brief WasmModule 构造函数
     @param url 指定连接的服务器
     @param protocol 指定握手协议，缺省为 ""
     @param origin 指定握手时模拟的源，缺省为 ""
    */
    WasmModule(String url, String protocol = "", String origin = "");
};
