/*! @brief base32 encoding and decoding module 
  Quote method: 
  `` `Javascript 
  var encoding = reques ('enCoding'); 
  var base32 = encoding.base32; 
  `` ` 
  or 
  `` `Javascript 
  var base32 = reques ('base32'); 
  `` `*/
module base32
{
    /*! @brief encoded data in base32 method 
 @param data to encode data 
 @Return Return the encoded string*/
    static String encode(Buffer data);

    /*! @brief decoded the string as binary data in the base32 method 
 @param data string to decoding 
 @Return Return to decoding binary data*/
    static Buffer decode(String data);
};
