/*! @brief base64 encoding and decoding module 
  Quote method: 
  `` `Javascript 
  var encoding = reques ('enCoding'); 
  var base64 = encoding.base64; 
  `` ` 
  or 
  `` `Javascript 
  var base64 = reques ('base64'); 
  `` `*/
module base64
{
    /*! @Brief encoded data in a base64 way 
 @param data to encode data 
 @Param URL specifies whether to use URL security character encoding 
 @Return Return the encoded string*/
    static String encode(Buffer data, Boolean url = false);

    /*! @brief decoding the string in the base64 method as the binary data 
 @param data string to decoding 
 @Return Return to decoding binary data*/
    static Buffer decode(String data);
};
