/*! @brief Message processor chain processing object 

  Message processor chain processing object is used to link a series of message processors, which are treated in the specified order. Create method: 
  `` `Javascript 
  var chain = new mq.chain ([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[ 
    func1, func2 
  ]); 
  `` `*/
interface Chain : Handler
{
    /*! @brief Construct a message processor chain processing object 
      @Param HDLRS processor array*/
    Chain(Array hdlrs);

    /*! @Brief Add a processor array 
      @Param HDLRS processor array*/
    append(Array hdlrs);

    /*! @brief adds a processor 
      @Param HDLR built -in message processor, processing function, chain processing array, routing object, see mq.handler for details*/
    append(Handler hdlr);
};
