/*! @brief encoding and decoding module, used to process the conversion between different data coding formats and binary 
  Quote method: 
  `` `Javascript 
  var encoding = reques ('enCoding'); 
  `` `*/
module encoding
{
    /*! @brief base32 encoding and decoding module*/
    static base32;

    /*! @brief base64 encoding and decoding module*/
    static base64;

    /*! @brief base58 encoding and decoding module*/
    static base58;

    /*! @brief hex encoding and decoding module*/
    static hex;

    /*! @Brief Multibase encoding and decoding module*/
    static multibase;

    /*! @Brief iconv encoding and decoding module*/
    static iconv;

    /*! @brief json encoding and decoding module*/
    static json;

    /*! @Brief msgpack encoding and decoding module*/
    static msgpack;

    /*! @Brief encoded the string as a JavaScript rush string for JavaScript code containing text in the JavaScript code 
      @Param Str Code string 
      @Param json, whether to generate JSON compatible string 
      @Return Return the encoded string*/
    static String jsstr(String str, Boolean json = false);

    /*! @Brief URL string safety coding 
      @Param url to encode URL 
      @Return Return the encoded string*/
    static String encodeURI(String url);

    /*! @Brief URL components string string safe coding 
      @Param url to encode URL 
      @Return Return the encoded string*/
    static String encodeURIComponent(String url);

    /*! @Brief URL security string decoding 
      @Param url to decoding URL 
      @Return Returns the decoding string*/
    static String decodeURI(String url);
};
