/*! @brief event object 

 The purpose of controlling a set of fibrous downside through an event (the status of the event object is BOOL type)*/
interface Event : Lock
{
    /*! @brief event object constructor 
      @Param Value specifies whether to wait, wait for True, the default is false*/
    Event(Boolean value = false);

    /*! @brief determine whether the event object is true 
      @Return If the event is true, return True*/
    Boolean isSet();

    /*! @brief activation event (change the event status to true), and call pulse ()*/
    set();

    /*! @Brief activates all the fiber journey waiting for the incident*/
    pulse();

    /*! @brief reset event (change the event status to false)*/
    clear();

    /*! @brief Waiting for an event*/
    wait();
};
