/*! @brief file operation object, read and write for binary files 

  The file operation object is used to operate the binary files, and the FS module can be used to open and create files: 
  `` `Javascript 
  var f = fs.openfile ('test.txt'); 
  `` `*/
interface File : SeekableStream
{
    /*! @brief query the current file name*/
    readonly String name;

    /*! @brief query the current file descriptor*/
    readonly Integer fd;

    /*! @brief query the access permissions of the current file, Windows does not support this method 
      @Param Mode specified access to settings*/
    chmod(Integer mode) async;
};
