/*! @brief GUI module 

 Instructions: 
 `` `Javascript 
 var gui = request ('gui'); 
 `` `*/
module gui
{
    /*! @brief webview ie simulation version, specify IE7*/
    const IE7 = 7000;

    /*! @brief webview ie simulation version, specify IE8*/
    const IE8 = 8000;

    /*! @brief webview ie simulation version, specify IE9*/
    const IE9 = 9000;

    /*! @brief webview ie simulation version, specify IE10*/
    const IE10 = 10000;

    /*! @brief webview ie simulation version, specify IE11*/
    const IE11 = 11000;

    /*! @brief webview ie simulation version, specify EDGE*/
    const EDGE = 11001;

    /*Set the highest simulation version in the webview. When the system IE version is lower than this version, the installation version of the simulation system will be installed 
      @param Ver specifies IE simulation version*/
    static setVersion(Integer ver);

    /*! @brief opens a window and access the designated URL

     Support the following parameters:
     `` `Javascript
     {{
         "LEFT": 100, // The upper left corner of the window, automatically set the default system
         "Right": 100, // The upper left corner of the window, automatically set the default system
         "width": 100, // window width, automatic setting of the default system
         "Height": 100, // Window height, automatic setting of default systems
         "border": true, // Whether there are borders, default and border
         "CAPTION": TRUE, // Whether there is a title bar, the default is the title bar
         "resizable": true, whether it can change the size, the default can change
         "Maximize": False, whether to maximize the display, the default is not maximized
         "FullScreen": False, // Whether to display a full screen window, the default is not full screen
         "DEBUG": true, whether to output errors in WebView and console information, default display or inherit the global settings
     }
     `` `
     When the Width and Heights are set and the left or right is not set, the window will automatically stand in the middle
     @Param URL specified the URL, you can use FS: Path to access the local file system
     @param Opt open the window parameter
     @Return Return to open the window object*/
    static WebView open(String url, Object opt = {});

    /*! @Brief opens an empty browser window

     Support the following parameters:
     `` `Javascript
     {{
         "LEFT": 100, // The upper left corner of the window, automatically set the default system
         "Right": 100, // The upper left corner of the window, automatically set the default system
         "width": 100, // window width, automatic setting of the default system
         "Height": 100, // Window height, automatic setting of default systems
         "border": true, // Whether there are borders, default and border
         "CAPTION": TRUE, // Whether there is a title bar, the default is the title bar
         "resizable": true, whether it can change the size, the default can change
         "Maximize": False, whether to maximize the display, the default is not maximized
         "FullScreen": False, // Whether to display a full screen window, the default is not full screen
         "DEBUG": true, whether to output errors in WebView and console information, default display or inherit the global settings
     }
     `` `
     When the Width and Heights are set and the left or right is not set, the window will automatically stand in the middle
     @param Opt open the window parameter
     @Return Return to open the window object*/
    static WebView open(Object opt = {});
};
