/*! @brief information summary calculation module, which can be used to calculate information summary and summary signature*/
module hash
{
    /*! @Brief MD5 Information Abstract Algorithm Identity Constitution*/
    const MD5 = 1;

    /*! @Brief SHA1 Information Abstract Algorithm Idential Constitution*/
    const SHA1 = 2;

    /*! @Brief SHA224 Information Abstract Algorithm Identan Metal*/
    const SHA224 = 3;

    /*! @Brief SHA256 Information Abstract Algorithm Identity Constitution*/
    const SHA256 = 4;

    /*! @Brief SHA384 Information Abstract Algorithm Identity Constitution*/
    const SHA384 = 5;

    /*! @Brief SHA512 Information Abstract Algorithm Identity Constitution*/
    const SHA512 = 6;

    /*! @Brief Ripemd160 Information Abstract Algorithm Identity Constitution*/
    const RIPEMD160 = 7;

    /*ly*/
    const SM3 = 8;

    /*! @Brief KECCAK256 Information Abstract Algorithm Identity Constitution*/
    const KECCAK256 = 9;

    /*! @Brief KECCAK384 Information Abstract Algorithm Identan Metal*/
    const KECCAK384 = 10;

    /*! @Brief KECCAK512 Information Abstract Algorithm Identan Metal*/
    const KECCAK512 = 11;

    /*! @Brief Blake2s Information Abstract Algorithm Identity Constitution*/
    const BLAKE2S = 12;

    /*! @Brief Blake2b Information Abstract Algorithm Identan Metal*/
    const BLAKE2B = 13;

    /*! @Brief Blake2SP Information Abstract Algorithm Identity Constitution*/
    const BLAKE2SP = 14;

    /*! @Brief Blake2bp Information Abstract Algorithm Identity Constitution*/
    const BLAKE2BP = 15;

    /*! @brief creates an information summary operation object based on the specified algorithm identification 
      @Param Algo specified abstract computing algorithm 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest digest(Integer algo, Buffer data = null);

    /*! @brief Create a MD5 information abstract operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest md5(Buffer data = null);

    /*! @brief Create a SHA1 information abstract operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest sha1(Buffer data = null);

    /*! @brief Create a SHA224 information abstract operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest sha224(Buffer data = null);

    /*! @brief Create a SHA256 information abstract operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest sha256(Buffer data = null);

    /*! @brief Create a SHA384 information abstract operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest sha384(Buffer data = null);

    /*! @brief Create a SHA512 information abstract operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest sha512(Buffer data = null);

    /*! @brief Create a RipeMD160 information summary operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest ripemd160(Buffer data = null);

    /*! @brief Create a SM3 information summary operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest sm3(Buffer data = null);

    /*! @brief Create a SM3 information summary operation object and prepare pre -processing 
      @param Pubkey Signature Public Key 
      @Param ID signature ID 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest sm3(PKey pubKey, String id, Buffer data = null);

    /*! @brief Create a KECCAK256 information summary operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest keccak256(Buffer data = null);

    /*! @brief Create a KECCAK384 information summary operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest keccak384(Buffer data = null);

    /*! @brief Create a KECCAK512 information summary operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest keccak512(Buffer data = null);

    /*! @brief Create a Blake2S information summary operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest blake2s(Buffer data = null);

    /*! @brief Create a Blake2b information summary operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest blake2b(Buffer data = null);

    /*! @brief Create a Blake2SP information summary operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest blake2sp(Buffer data = null);

    /*! @brief Create a Blake2bp information summary operation object 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest blake2bp(Buffer data = null);

    /*! @brief Create an information summary computing object based on the specified algorithm identification 
      @Param Algo specified abstract computing algorithm 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac(Integer algo, Buffer key, Buffer data = null);

    /*! @brief Create a MD5 information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_md5(Buffer key, Buffer data = null);

    /*! @brief Create a SHA1 Information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_sha1(Buffer key, Buffer data = null);

    /*! @brief Create a SHA224 information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_sha224(Buffer key, Buffer data = null);

    /*! @brief Create a SHA256 information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_sha256(Buffer key, Buffer data = null);

    /*! @brief Create a SHA384 information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_sha384(Buffer key, Buffer data = null);

    /*! @brief Create a SHA512 information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_sha512(Buffer key, Buffer data = null);

    /*! @brief Create a RipeMD160 information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_ripemd160(Buffer key, Buffer data = null);

    /*! @brief Create a SM3 Information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_sm3(Buffer key, Buffer data = null);

    /*! @brief Create a SM3 Information Abstract Signature Computing Object and Pre -processing 
      @param Pubkey Signature Public Key 
      @Param ID signature ID 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_sm3(PKey pubKey, String id, Buffer key, Buffer data = null);

    /*! @brief Create a KECCAK256 information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_keccak256(Buffer key, Buffer data = null);

    /*! @brief Create a KECCAK384 information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_keccak384(Buffer key, Buffer data = null);

    /*! @brief Create a KECCAK512 information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_keccak512(Buffer key, Buffer data = null);

    /*! @brief Create a Blake2S information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_blake2s(Buffer key, Buffer data = null);

    /*! @brief Create a Blake2b information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_blake2b(Buffer key, Buffer data = null);

    /*! @brief Create a Blake2SP information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_blake2sp(Buffer key, Buffer data = null);

    /*! @brief Create a Blake2bp information Abstract Signature Computing Object 
      @Param KEY binary signature key 
      @Param Data Create the binary data updated at the same time, the default is NULL, not updated the data 
      @Return Returns the information abstract object of the structure*/
    static Digest hmac_blake2bp(Buffer key, Buffer data = null);
};
