/*! @Brief Heapgraphnode indicates a node in the stack view*/
interface HeapGraphNode : object
{
    /*! @brief node type, possible value: 
      -PROFILER.NODE_HIDDEN, hidden nodes, can be filtered out when it is displayed to the user 
      -PROFILER.NODE_ARAY, array 
      -PROFILER.NODE_STRING, String 
      -PROFILER.NODE_OBJECT, JS object (except string and array) 
      -PROFILER.NODE_CODE, compiled code 
      -PROFILER.NODE_CLOSURE, function closure 
      -PROFILER.NODE_REGEXP, regular expression formula 
      -PROFILER.NODE_HEAPNUMBER, numerals excreted in the pile 
      -PROFILER.NODE_NATIVE, Native object (non -V8 pile) 
      -PROFILER.NODE_SYNTHETIC, Synthetic object 
      -PROFILER.NODE_CONSSTRING, stringed string string 
      -PROFILER.NODE_SLICEDSTRING, split string 
      -PROFILER.NODE_SYMBOL, Symbol (ES6) 
      -PROFILER.NODE_SIMDVALUE, sIMD value exclusive in the heap (ES7)*/
    readonly Integer type;

    /*! @brief node name*/
    readonly String name;

    /*! @Brief Node's Description*/
    readonly String description;

    /*! @brief node ID*/
    readonly Integer id;

    /*! @brief node size, the unit is byte*/
    readonly Integer shallowSize;

    /*! @brief sub -node list, consisting of Heapgraphedge type object*/
    readonly NArray childs;
};
