/*! @Brief Heapsnapshots recorded JS stacked at a certain moment*/
interface HeapSnapshot : object
{
    /*! @brief and specified heap snapshot for comparison 
      @Param Before to compare the pile of snapshots 
      @Return Return to the comparison of the stacking snapshot*/
    Object diff(HeapSnapshot before);

    /*! @Brief obtains the pile view node according to the ID 
      @param ID Node ID 
      @Return Return to the obtained pile view node*/
    HeapGraphNode getNodeById(Integer id);

    /*! @Brief save heapsnapshot according to the specified name 
      @param FNAME snapshot name*/
    save(String fname) async;

    /*! @brief Time Information*/
    readonly Date time;

    /*! @Brief Back Node*/
    readonly HeapGraphNode root;

    /*! @Brief Packing View Specket Composition List*/
    readonly NArray nodes;
};
