/*! @brief hex encoding and decoding module 
  Quote method: 
  `` `Javascript 
  var encoding = reques ('enCoding'); 
  var hex = encoding.hex; 
  `` ` 
  or 
  `` `Javascript 
  var hex = request ('hex'); 
  `` `*/
module hex
{
    /*! @brief encoded data in Hex mode 
 @param data to encode data 
 @Return Return the encoded string*/
    static String encode(Buffer data);

    /*! @brief decoded the string as a binary data in the hex mode 
 @param data string to decoding 
 @Return Return to decoding binary data*/
    static Buffer decode(String data);
};
