/*! @Brief contains a entry data of Multipart*/
interface HttpUploadData : object
{
    /*! @Brief contains the file name of the data of this entry*/
    readonly String fileName;

    /*! @Brief contains the type of this entry data*/
    readonly String contentType;

    /*! @Brief contains the transmission coding type of this item data*/
    readonly String contentTransferEncoding;

    /*! @Brief contains the flow object of the data part of this item*/
    readonly SeekableStream body;
};
