/*! @Brief HTTPS server object 

  The HTTPS server object is the object that encapsulates SSLSERVER and HTTPHANDLER to facilitate quickly building the server, which is logically equivalent to: 
  `` `Javascript 
  var svr = new network.sslserver (CRT, key, addr, port, new http.handler (function (reQ) { 
     Em 
  }); 
  `` ` 

  Create method: 
  `` `Javascript 
  var http = request ("http"); 
  var svr = new http.httpsserver (CRT, key, 443, function (reQ) { 
      Em 
  }); 
  `` `*/
interface HttpsServer : HttpServer
{
    /*! @Brief httpsserver constructor, listening to all the address of this machine 

     Certs format: 
     `` `Javascript 
     
         {{ 
             name: "fibjs.org", 
             CRT: [X509cert Object], 
             Key: [pKEY Object] 
         }, 
         {{ 
             name: "*.fibjs.org", 
             CRT: [X509cert Object], 
             Key: [pKEY Object] 
         } 
     ] 
     `` ` 
     @Param Certs server certificate list 
     @Param Port specifies the HTTP server listening port 
     @Param HDLR HTTP built -in message processor, processing function, chain processing array, routing object, see*/
    HttpsServer(Array certs, Integer port, Handler hdlr);

    /*! @brief httpsserver constructor 

     Certs format: 
     `` `Javascript 
     
         {{ 
             name: "fibjs.org", 
             CRT: [X509cert Object], 
             Key: [pKEY Object] 
         }, 
         {{ 
             name: "*.fibjs.org", 
             CRT: [X509cert Object], 
             Key: [pKEY Object] 
         } 
     ] 
     `` ` 
     @Param Certs server certificate list 
     @Param ADDR specify the HTTP server to listen to the address, to "" all addresses in this machine to listen to 
     @Param Port specifies the HTTP server listening port 
     @Param HDLR HTTP built -in message processor, processing function, chain processing array, routing object, see*/
    HttpsServer(Array certs, String addr, Integer port, Handler hdlr);

    /*! @Brief httpsserver constructor, listening to all the address of this machine 
     @Param CRT X509cert certificate for client verification server 
     @Param KEY PKEY private key, used to talk to the client 
     @Param Port specifies the HTTP server listening port 
     @Param HDLR HTTP built -in message processor, processing function, chain processing array, routing object, see*/
    HttpsServer(X509Cert crt, PKey key, Integer port, Handler hdlr);

    /*! @brief httpsserver constructor 
     @Param CRT X509cert certificate for client verification server 
     @Param KEY PKEY private key, used to talk to the client 
     @Param ADDR specify the HTTP server to listen to the address, to "" all addresses in this machine to listen to 
     @Param Port specifies the HTTP server listening port 
     @Param HDLR HTTP built -in message processor, processing function, chain processing array, routing object, see*/
    HttpsServer(X509Cert crt, PKey key, String addr, Integer port, Handler hdlr);

    /*! @brief Set the certificate verification mode, the default is Verify_none*/
    Integer verification;

    /*! @brief client certificate verification CA*/
    readonly X509Cert ca;
};
