/*! @Brief HTTP protocol conversion processor 

   Used to convert data to the HTTP protocol message and create: 
   `` `Javascript 
   var hdlr = new mq.httphandler (...); 
   `` ` 
   or: 
   `` `Javascript 
   var hdlr = new http.handler (...); 
   `` `*/
interface HttpHandler : Handler
{
    /*! @brief Create an object of HTTP protocol processor, transform the data of the flow object to the HTTP message object 
     @Param HDLR built -in message processor, processing function, chain processing array, routing object, see mq.handler for details*/
    HttpHandler(Handler hdlr);

    /*! @brief allows cross -domain requests 
      @param Allowheaders specify the acceptable HTTP head field*/
    enableCrossOrigin(String allowHeaders = "Content-Type");

    /*! @brief query and set the maximum request number, the default is 128*/
    Integer maxHeadersCount;

    /*! @brief query and set the maximum size of body, in mb as the unit, the default is 64*/
    Integer maxBodySize;

    /*! @Brief automatically decompressed the function switch, turn off by default*/
    Boolean enableEncoding;

    /*! @brief query and set the server name, the default is: fibjs/0.x.0*/
    String serverName;

    /*! @Brief HTTP protocol conversion processor current event processing interface object*/
    Handler handler;
};
