/*! @Brief HTTP server object 

  The HTTP server object is the object that encapsulates the TCPSERVER and HTTPHANDLER combination, which is convenient to quickly build the server. Logicly, it is equivalent to: 
  `` `Javascript 
  var svr = new network.tcpserver (addr, port, new http.handler (function (reQ) { 
     Em 
  }); 
  `` ` 

  Create method: 
  `` `Javascript 
  var http = request ("http"); 
  var svr = new http.server (80, function (reQ) { 
      Em 
  }); 
  `` `*/
interface HttpServer : TcpServer
{
    /*! @Brief httpserver constructor, listening to all the address of this machine 
     @Param Port specifies the HTTP server listening port 
     @Param HDLR HTTP built -in message processor, processing function, chain processing array, routing object, see mq.handler for details*/
    HttpServer(Integer port, Handler hdlr);

    /*! @Brief httpserver constructor 
     @Param ADDR specify the HTTP server to listen to the address, to "" all addresses in this machine to listen to 
     @Param Port specifies the HTTP server listening port 
     @Param HDLR HTTP built -in message processor, processing function, chain processing array, routing object, see mq.handler for details*/
    HttpServer(String addr, Integer port, Handler hdlr);

    /*! @Brief httpserver constructor 
     @Param ADDR specify the HTTP server to listen to the address, to "" all addresses in this machine to listen to 
     @Param HDLR HTTP built -in message processor, processing function, chain processing array, routing object, see mq.handler for details*/
    HttpServer(String addr, Handler hdlr);

    /*! @brief allows cross -domain requests 
      @param Allowheaders specify the acceptable HTTP head field*/
    enableCrossOrigin(String allowHeaders = "Content-Type");

    /*! @brief query and set the maximum request number, the default is 128*/
    Integer maxHeadersCount;

    /*! @brief query and set the maximum size of body, in mb as the unit, the default is 64*/
    Integer maxBodySize;

    /*! @Brief automatically decompressed the function switch, turn off by default*/
    Boolean enableEncoding;

    /*! @brief query and set the server name, the default is: fibjs/0.x.0*/
    String serverName;
};
