/*! @brief http request message object*/
interface HttpRequest : HttpMessage
{
    /*! @brief httprequest constructor to create a new HTTPRequest object*/
    HttpRequest();

    /*! @brief Get the response message object*/
    readonly HttpResponse response;

    /*! @brief query and set the request method*/
    String method;

    /*! @brief query and set the request address*/
    String address;

    /*! @brief query and set the request query string*/
    String queryString;

    /*! @brief Get the container containing message cookies*/
    readonly HttpCollection cookies;

    /*! @brief Get the container containing message form*/
    readonly HttpCollection form;

    /*! @brief Get the container containing message Query*/
    readonly HttpCollection query;
};
