/*! @brief json encoding and decoding module 
  Quote method: 
  `` `Javascript 
  var encoding = reques ('enCoding'); 
  var json = encoding.json; 
  `` ` 
  or 
  `` `Javascript 
  var json = reques ('json'); 
  `` `*/
module json
{
    /*! @Brief encoded variables in JSON format 
 @param data to encode variables 
 @Return Return the encoded string*/
    static String encode(Value data);

    /*! @Brief decoded the string as a variable in JSON mode 
 @param data string to decoding 
 @Return Return to decoding variables*/
    static Value decode(String data);
};
