/*! @brief leveldb database object 

  Used to create and manage dictionary objects, create methods: 
  `` `Javascript 
  varb = request ("db"); 
  var test = new db.openleveldb ("test.db"); 
  `` `*/
interface LevelDB : object
{
    /*! @brief check the data of the specified key value in the database 
      @Param key Specify the key value you want to check 
      @Return Return the key value exists*/
    Boolean has(Buffer key) async;

    /*! @brief query the value of the specified key value 
      @Param key Specify the key value you want to query 
      @Return Returns the value corresponding to the key value, if it does not exist, return NULL*/
    Buffer get(Buffer key) async;

    /*! @brief query a set of values of a set of specified key values 
      @Param keys specifies the key value array you want to query 
      @Return Return to contain a key worth the array*/
    NArray mget(Array keys);

    /*! @Brief Set a key data data, the key value does not exist, and insert new data 
      @Param Key specify the key value to be set 
      @Param Value specify data to be set*/
    set(Buffer key, Buffer value) async;

    /*! @brief Set a set of key data data, the key value does not exist and insert new data 
      @Param Map specifies the key value data dictionary to be set*/
    mset(Object map);

    /*! @brief Delete a set of values of specified key values 
      @Param keys specifies the key value array to be deleted*/
    mremove(Array keys);

    /*! @brief deletes all the value of the specified key value 
      @Param Key specify the key value to be deleted*/
    remove(Buffer key) async;

    /*! @brief enumerated all the key values in the database 

      There are two parameters of the callback function, (Value, key) 

      `` `Javascript 
      varb = request ("db"); 
      var test = new db.openleveldb ("test.db"); 

      Test.Foreach (function (value, key) { 
         Em 
      }); 
      `` ` 
      @param func enumeration back adjustment function*/
    forEach(Function func);

    /*! @Brief enumerated the key value between the key value between the from and to in the database 

      There are two parameters of the callback function, (Value, key) 

      `` `Javascript 
      varb = request ("db"); 
      var test = new db.openleveldb ("test.db"); 

      test.between ("AAA", "BBB", Function (Value, Key) { 
         Em 
      }); 
      `` ` 
      @Param from the minimum key value of enumeration, contain this key value when enumerated 
      @Param to enumerate the maximum key value, this key value is not included when enumerated 
      @param func enumeration back adjustment function*/
    between(Buffer from, Buffer to, Function func);

    /*! @brief opens a transaction on the current database 
      @Return Return to an open transaction object*/
    LevelDB begin();

    /*! @brief Submit the current transaction*/
    commit();

    /*! @brief Turn off the current database connection or transaction*/
    close() async;
};
