/*! @brief Memory Stream Object 

  Memorystream object creates a memory -based stream object, creating method: 
  `` `Javascript 
  varm ms = new IO.MemoryStream (); 
  `` `*/
interface MemoryStream : SeekableStream
{
    /*! @Brief Memorystream constructor*/
    MemoryStream();

    /*ly 
      @param d specifies the time to be set*/
    setTime(Date d);

    /*! @brief Create a copy of the current memory flow. 
      @Return Returns the memory flow object that only reads*/
    MemoryStream clone();

    /*! @brief empty memory file data, reset pointer*/
    clear();
};
