/*! @Brief Mongodb database connection object 

  Create with db.open or db.openmongodb to create: 
  `` `Javascript 
  var mdb = db.openmongodb ("mongodb: // host/db"); 
  `` `*/
interface MongoDB : object
{
    /*! @brief Get the specified collection access object 
     @param name Specify the name of the collection 
     @Return Return to the specified collection object*/
    MongoCollection getCollection(String name);

    /*! @Brief specify a MongoDB database command 
     @Param CMD specifies the dictionary object of the command and parameter 
     @Return Return the command execution result*/
    Object runCommand(Object cmd);

    /*! @Brief specify a simple MongoDB database command 
     @Param cmd specified command name 
     @param arg specify command parameters 
     @Return Return the command execution result*/
    Object runCommand(String cmd, Value arg);

    /*! @brief quickly get the specified collection access object 

    Used to quickly obtain a collection object with attributes, such as: 
    `` `Javascript 
    var test = mdb.test; 
    `` `*/
    readonly MongoCollection operator[String];

    /*! @Brief generate a mongodb_Objectid object 
     @Param Hexstr Initialize the hexadecimal string, default to generate new ID 
     @Return*/
    MongoID oid(String hexStr = "");

    /*! @brief Turn off the current database connection*/
    close() async;
};
