/*! @Brief Mongodb database data cursor object*/
interface MongoCursor : object
{
    /*! @brief specifies the number of records that jump when the return result 
     @Param NUM Records 
     @Return Return the cursor object itself is convenient for chain calls*/
    MongoCursor skip(Integer num) async;

    /*! @brief specifies the maximum record of the return result 
     @Param Size record number 
     @Return Return the cursor object itself is convenient for chain calls*/
    MongoCursor limit(Integer size) async;

    /*! @brief Set the sort of the return result 
     @param Opts specified sorting conditions 
     @Return Return the cursor object itself is convenient for chain calls*/
    MongoCursor sort(Object opts);

    /*! @brief check whether the current cursor has the next record 
     @Return has a record and returns true*/
    Boolean hasNext();

    /*! @brief Return to the next record of the current cursor 
     @Return Record object, without records, return NULL*/
    Object next();

    /*! @brief Inquiry Cassert Call for Casters 
     @Param Applyskiplimit specifies the number of records after SKIP and Limit, the default is false, query the entire record number 
     @Return Return to the total number of records*/
    Integer count(Boolean applySkipLimit = false);

    /*! @Brief query the total number of records of the cursor, which is equivalent to count (true) 
     @Return Return to the total number of records*/
    Integer size();

    /*! @brief traversed all records and recovered processing functions 
     @param func specified processing function*/
    forEach(Function func);

    /*! @brief traversed all records and returned to the process of processing 
     @param func specified processing function 
     @Return Return to process results*/
    Array map(Function func);

    /*! @brief Return to the array of all the current records of the current cursor 
    @Return Returns the JavaScript array containing all data*/
    Array toArray();

    /*! @Brief Modify the MongoDB server default index strategy and use the specified index for query 
     @param Opts specify the index of forced use 
     @Return Return the cursor object itself is convenient for chain calls*/
    MongoCursor hint(Object opts);
};
