/*! @brief mysql database connection object 

  Create with db.open or db.openmysql to create: 
  `` `Javascript 
  var mysql = db.openmysql ("mysql: // user: pass@host/db"); 
  `` `*/
interface MySQL : DbConnection
{
    /*! @brief database connection to receive cache size*/
    Integer rxBufferSize;

    /*! @brief database connection to send cache size*/
    Integer txBufferSize;
};
