/*! @brief basic object, all objects inherited here*/
interface object
{
    /*! @Brief returned the string of the object, which generally returned "native object], and the object can be re -realized according to its own characteristics 
      @Return Return the string of the object*/
    String toString();

    /*! @Brief returned to the JSON format of the object of the object, generally the readable attribute collection defined by the object definition 
      @Param Key 
      @Return Returns the value that contains JSON serialization*/
    Value toJSON(String key = "");
};
