/*! @Brief Punycode international domain name conversion module 

  Punycode is a character encoding scheme mainly used for international domain names defined by RFC 3492. Because the host name limit in the URL can only be ASCII characters, including the host name of non -ASCII characters must be converted into ASCII with the PunyCode algorithm. 

  Instructions: 
  `` `Javascript 
  var Punycode = reques ('Punycode'); 
  `` `*/
module punycode
{
    /*! @Brief converts a unicode string into a PunyCode string containing only ASCII characters 
 @Param Domain given Unicode string 
 @Return Return the PunyCode string containing only ASCII characters after encoding*/
    static String encode(String domain);

    /*! @Brief converts a PUNYCode string into an equivalent Unicode string 
 @Param Domain given Unicode string 
 @Return Returns the decoding Unicode string*/
    static String decode(String domain);

    /*! @Brief converts a unicode string that represents a domain name is a string containing only ASCII characters. Only the non -ASCII string representing the part of the domain name will be converted. In other words, if you call a string that has been converted into ASCII, there is no problem. 
 @Param Domain given Unicode string 
 @Return Return the encoded ASCII string*/
    static String toASCII(String domain);

    /*! @Brief converts a PunyCode string representing a domain name as a unicode string. Only the PunyCode string representing the part of the domain name will be converted. In other words, if you call a string that has been converted into Unicode, it is also no problem. 
 @Param Domain given ASCII string 
 @Return Returns the decoding Unicode string*/
    static String toUnicode(String domain);
};
