/*! @brief can move the current pointer flow object interface*/
interface SeekableStream : Stream
{
    /*! @brief mobile file current operation location 
       @param Offset specifies the new location 
       @Param When specifies the position benchmark, the allowable value is: Seek_Set, Seek_cur, Seek_END*/
    seek(Long offset, Integer whence = fs.SEEK_SET);

    /*! @brief query stream current position 
      @Return Return to the current location*/
    Long tell();

    /*! @brief Move the current position to the beginning of the stream*/
    rewind();

    /*! @brief query stream size 
      @Return Return the stream size*/
    Long size();

    /*! @Brief read all the remaining data from the stream 
      @Return returns the data read from the stream. If there is no data to read, or the connection is interrupted, then return NULL*/
    Buffer readAll() async;

    /*! @brief Modify the size of the file. If the new size is less than the original size, the file is cut off 
       @param bytes new file size*/
    truncate(Long bytes) async;

    /*! @brief query the file to the end 
      @Return Return True to represent the ending*/
    Boolean eof();

    /*! @brief Query the basic information of the current file 
      @Return Return the STAT object description file information*/
    Stat stat() async;
};
