/*! @Brief SQLite Database Connection Object 

  Create with db.open or db.opensqlite to create: 
  `` `Javascript 
  var slite = db.opensqlite ("sqlite:/path/to/db"); 
  `` `*/
interface SQLite : DbConnection
{
    /*! @brief The current database file name*/
    readonly String fileName;

    /*! @brief query and set the database timeout time, in milliseconds*/
    Integer timeout;

    /*! @brief Back up the current database to the new file 
 @Param Filename specified the backup database file name*/
    backup(String fileName) async;
};
