/*! @Brief SSL server object, it is convenient to create a standard multi -fiber SSL server 

 The SSLSERVER object is the object that encapsulates TCPSERVER and SSLHANDLER to facilitate quickly building the server. It is logically equivalent to: 
  `` `Javascript 
  var svr = new network.sslserver (addr, port, new ssl.handler (CRT, key, function (REQ) { 
     Em 
  }); 
  `` ` 

  Create method: 
  `` `Javascript 
  var ssl = request ("ssl"); 
  var svr = New http.server (CRT, key, Function (REQ) { 
      Em 
  }); 
  `` `*/
interface SslServer : TcpServer
{
    /*! @Brief SSLSERVER constructor, listening to all the address of this machine 

     Certs format: 
     `` `Javascript 
     
         {{ 
             name: "fibjs.org", 
             CRT: [X509cert Object], 
             Key: [pKEY Object] 
         }, 
         {{ 
             name: "*.fibjs.org", 
             CRT: [X509cert Object], 
             Key: [pKEY Object] 
         } 
     ] 
     `` ` 
     @Param Certs server certificate list 
     @Param Port specify SSL server listening port 
     @Param Listener specifies the built -in message processor received by SSL, processing functions, chain processing array, routing object, see mq.handler for details*/
    SslServer(Array certs, Integer port, Handler listener);

    /*! @Brief SSLSERVER constructor 

     Certs format: 
     `` `Javascript 
     
         {{ 
             name: "fibjs.org", 
             CRT: [X509cert Object], 
             Key: [pKEY Object] 
         }, 
         {{ 
             name: "*.fibjs.org", 
             CRT: [X509cert Object], 
             Key: [pKEY Object] 
         } 
     ] 
     `` ` 
     @Param Certs server certificate list 
     @Param ADDR specify the SSL server listening address, for "" all addresses in this machine to listen to 
     @Param Port specify SSL server listening port 
     @Param Listener specifies the built -in message processor, processing function, chain processing array, routing object, please refer to mq.handler*/
    SslServer(Array certs, String addr, Integer port, Handler listener);

    /*! @Brief SSLSERVER constructor, listening to all the address of this machine 
     @Param CRT X509cert certificate for client verification server 
     @Param KEY PKEY private key, used to talk to the client 
     @Param Port specify SSL server listening port 
     @Param Listener specifies the built -in message processor received by SSL, processing functions, chain processing array, routing object, see mq.handler for details*/
    SslServer(X509Cert crt, PKey key, Integer port, Handler listener);

    /*! @Brief SSLSERVER constructor 
     @Param CRT X509cert certificate for client verification server 
     @Param KEY PKEY private key, used to talk to the client 
     @Param ADDR specify the SSL server listening address, for "" all addresses in this machine to listen to 
     @Param Port specify SSL server listening port 
     @Param Listener specifies the built -in message processor, processing function, chain processing array, routing object, please refer to mq.handler*/
    SslServer(X509Cert crt, PKey key, String addr, Integer port, Handler listener);

    /*! @brief Set the certificate verification mode, the default is Verify_none*/
    Integer verification;

    /*! @Brief Client Certificate Verification Certificate Chain*/
    readonly X509Cert ca;
};
