/*! @Brief File Basic Information Object 

   STAT objects query through fs.stat, file.stat, fs.readdir, and cannot be created independently*/
interface Stat : object
{
    /*! @brief file name*/
    readonly String name;

    /*! @Brief contains the device ID of the file*/
    readonly Integer dev;

    /*! @Brief file quantity*/
    readonly Integer ino;

    /*! @brief file permissions, Windows does not support this attribute*/
    readonly Integer mode;

    /*! @Brief The number of hard links associated with this file*/
    readonly Integer nlink;

    /*! @brief file owner's ID*/
    readonly Integer uid;

    /*! @Brief files belong to the group ID*/
    readonly Integer gid;

    /*! @brief For special types of files, device ID containing the file*/
    readonly Integer rdev;

    /*! @brief file size*/
    readonly Number size;

    /*ly*/
    readonly Integer blksize;

    /*! @Brief The number of blocks assigned to the file*/
    readonly Integer blocks;

    /*! @brief file last modified time*/
    readonly Date mtime;

    /*! @brief File Last Modification Time (MS)*/
    readonly Number mtimeMs;

    /*! @brief file last visit time*/
    readonly Date atime;

    /*! @brief file last visit time (MS)*/
    readonly Number atimeMs;

    /*! @brief file creation time*/
    readonly Date ctime;

    /*! @brief file creation time (MS)*/
    readonly Number ctimeMs;

    /*! @brief file generate time*/
    readonly Date birthtime;

    /*! @brief file generated time (MS)*/
    readonly Number birthtimeMs;

    /*! @brief query the file whether there is writing permissions 
      @Return is TRUE, there is writing permissions*/
    Boolean isWritable();

    /*! @brief query whether there is read permissions 
      @Return is true, there is read permissions*/
    Boolean isReadable();

    /*! @brief query whether there is execution permissions 
      @Return is true, there is execution permissions*/
    Boolean isExecutable();

    /*! @brief query whether the file is hidden 
      @Return is true hidden*/
    Boolean isHidden();

    /*! @Brief query whether the stat describes a block device 
      @Return describes a block device for True*/
    Boolean isBlockDevice();

    /*! @Brief query whether the stat describes a chaper device 
      @Return describes a Character Device for True*/
    Boolean isCharacterDevice();

    /*! @brief query file is the directory 
      @Return is true is a directory*/
    Boolean isDirectory();

    /*! @brief query whether the STAT describes a FIFO pipeline 
      @Return describes a FIFO pipeline for TRUE*/
    Boolean isFIFO();

    /*! @brief query the file is the file 
      @Return is true is a file*/
    Boolean isFile();

    /*! @brief query file is a symbolic link 
      @Return is true is a symbolic link*/
    Boolean isSymbolicLink();

    /*! @brief query file is a memory file 
      @Return is true is memory file*/
    Boolean isMemory();

    /*! @brief query file is a socket 
      @Return is true is socket*/
    Boolean isSocket();
};
