/*! @brief flow decoding object*/
interface StringDecoder : object
{
    /*! @brief decoder constructor 
      @Param Encoding decoding coding. The default 'utf8'.*/
    StringDecoder(String encoding = "utf8");

    /*! @brief returns the buffer inside as a character. Incant UTF-8 and UTF-16 bytes will try to make up. 
      @Return decoded string.*/
    String end();

    /*! @brief returns the buffer inside as a character. Incant UTF-8 and UTF-16 bytes will try to make up. 
      @Param BUF needs to decoder. Before executing the END, you will call WRITE to write Buffer. 
      @Return decoded string.*/
    String end(Buffer buf);

    /*! @brief returns a decoding string to ensure that any non -complete end -ended character is omitted this time and is stored in the WRITE or END method for the next time. 
      @Param BUF needs to decoder. 
      @Return decoded string.*/
    String write(Buffer buf);

    /*! @brief inside. Then, then, then 
      @Param BUF needs to decoder. 
      @param Offset decoding offset 
      @Return decoded string.*/
    String text(Buffer buf, Integer offset);

    /*! @brief inside. Then, then, then 
      @param buf a buffer containing the bytes to decode. 
      @Return decoded string.*/
    String fillLast(Buffer buf);

    /*! @brief inside.*/
    Integer lastNeed;

    /*! @brief inside.*/
    Integer lastTotal;

    /*! @brief inside.*/
    Buffer lastChar;

    /*! @brief decoding coding. Internal use.*/
    String encoding;
};
