/*! @brief decoder buffer to string 

  Instructions: 
  `` `Javascript 
   const {StringDecoder} = reques ('String_decoder'); 
   const decoder = New StringDecoder ('UTF8'); 

   const center = buffer.from ([0xc2, 0xa2]); 
   console.log (decoder.write (center)); 

   const Euro = buffer.from ([0xe2, 0x82, 0xac]); 
   console.log (decoder.write (euro)); 
  `` `*/
module string_decoder
{
    /*! @brief Create a decoding object, see StringDecoder*/
    static StringDecoder new StringDecoder();
};
