/*! @brief tty module 

  Instructions: 
  `` `Javascript 
  const tty = request ('tty'); 
  `` `*/
module tty
{
    /*! @brief query whether it is the command interactive window 
     @Param FD file descriptor 
      @Return If the file descriptor is associated with the same terminal window, it returns true, otherwise it will return false*/
    static Boolean isatty(Integer fd);
};
