/*! @Brief URL processing module*/
module url
{
    /*! @Brief parameter constructed URLOBject object 
      @Param ARGS specifies the dictionary object of the constructive parameter. The supporting fields are: Protocol, Slashes, Username, Password, Hostname, PATHNAME, QURY, Hash, Hash 
      @Return Return to a successful constructor string*/
    static String format(Object args);

    /*! @Brief Analysis of a URL string 
      @Param url specify the URL string that needs to be parsed 
      @param ParsequryString specifies whether to analyze Query 
      @Param Slashesdenotehost defaults to false, if set to true, then the string before the string to the next '/' will be parsed to host, such as '// foo/bar', the result should be {{ Host: 'FOO', PathName: '/Bar'} instead of {PathName: '// FOO/BAR'} 
      @Return Return to objects containing analytical data*/
    static UrlObject parse(String url, Boolean parseQueryString = false, Boolean slashesDenoteHost = false);

    /*! @brief Merge relative path becomes an absolute path 

      @param_from source path 
      @Param to relative path 
      @Return returned absolute path*/
    static String resolve(String _from, String to);

    /*! @Brief Create a Urlobject request object, see UrLOBject*/
    static UrlObject new URL();
};
