/*! @brief safety sandbox module, used to isolate the operating environment of different safety levels 

  By establishing a safety sandbox, resources that can be exposed to script can be limited, and different scripts can be used to execute the environment. They can customize basic modules for different environments to ensure the safety of the overall operating environment. 

  The following example creates a sandbox that limits only the access module in the global basic module, and adds two custom modules: A and B: 
  `` `Javascript 
  var vm = request ('vm'); 
  var sbox = new vm.sandbox ({{ 
    A: 100, 
    B: 200, 
    assert: Require ('Assert') 
  }); 

  var mod_in_sbox = sbox.require ('./ Path/to/mod'); 
  `` `*/
module vm
{
    /*! @Brief Create a Sandbox object, see Sandbox*/
    static SandBox new SandBox();
};
