/*! @Brief WebsoCket Message Object 

  Create method: 
  `` `Javascript 
  var WS = Require ("WS"); 

  var msg = new ws.message (); 
  `` `*/
interface WebSocketMessage : Message
{
    /*! @brief package processing message object constructor 
 @Param Type WebSocket Message Type, the default is websocket.binary 
 @Param Masked WebSocket Message Model Cushion, the default is TRUE 
     @Param Compress label message whether the message is compressed, the default is false 
 @Param Maxsize's largest package size, in MB as the unit, the default is 67108864 (64M)*/
    WebSocketMessage(Integer type = ws.BINARY, Boolean masked = true, Boolean compress = false, Integer maxSize = 67108864);

    /*! @Brief query and read WebSocket mask marking, the default is True*/
    Boolean masked;

    /*! @Brief query and read WebSocket compression status, the default is false*/
    Boolean compress;

    /*! @brief query and set the maximum package size, in byte, the default is 67108864 (64M)*/
    Integer maxSize;
};
