/*! @brief X509 Rejuvenation Certificate Object 

  X509CRL object belongs to the Crypto module, created: 
  `` `Javascript 
  var k = new crypto.x509crl (); 
  `` `*/
interface X509Crl : object
{
    /*! @Brief X509Crl constructor*/
    X509Crl();

    /*! @Brief X509Crl constructor, load a deer format withdrawal certificate 
      @Param dercrl der format's cancellation certificate*/
    X509Crl(Buffer derCrl);

    /*! @Brief X509Crl constructor, load a PEM format withdrawal certificate 
      @Param Pemcrl PEM format cancellation certificate*/
    X509Crl(String pemCrl);

    /*! @brief Load a deer format certificate, you can call it multiple times 
      @Param dercrl der format's cancellation certificate*/
    import(Buffer derCrl);

    /*! @brief load a PEM format's revocation certificate, you can call it multiple times 
      @Param Pemcrl PEM format cancellation certificate*/
    import(String pemCrl);

    /*! @Brief exported the withdrawal certificate that has been loaded in PEM format 
      @param all specifies whether to output all certificates, the default is TRUE 
      @Return exports the certificate chain in a array*/
    String pem(Boolean all = true);

    /*! @brief Export the withdrawal certificate that has been loaded in DER format 
      @Return exports the certificate chain in a array*/
    Buffer der();

    /*! @brief Clear Certificate that has been loaded*/
    clear();

    /*! @brief Get the certificate of the certificate*/
    readonly Integer version;

    /*! @Brief obtained the certificate of the certificate of the certificate of the certificate*/
    readonly String issuer;

    /*! @brief Get the certificate to revoke the sequence number list*/
    readonly Array serials;

    /*! @brief Get this update time for the certificate*/
    readonly Date thisUpdate;

    /*! @brief Get the next update time for the certificate*/
    readonly Date nextUpdate;

    /*! @brief Get the certificate in the certificate chain*/
    readonly X509Crl next;
};
