/*! @Brief XMLATTR object indicates the attributes of the XMLEMENT object*/
interface XmlAttr : object
{
    /*! @brief query the local name of the element. If the selected node has no name space, the attribute is equivalent to nodename*/
    readonly String localName;

    /*! @Brief attribute value*/
    String value;

    /*! @Brief Name of Properties*/
    readonly String name;

    /*! @Brief query the URI of the naming space of the element. If the selected node has no name space, the attribute returns NULL*/
    readonly String namespaceURI;

    /*! @brief query and set the naming space prefix. If the selected node has no name space, the attribute returns NULL*/
    String prefix;

    /*! @Brief's name, for a compatible purpose*/
    readonly String nodeName;

    /*! @Brief's value, for a compatible purpose*/
    String nodeValue;
};
