/*! @brief xmlcomment object represents the content of the annotation node in the documentation 

 XMLCOMMENT node represents comments in XML documents. 
 Using Data attributes inherited by XMLCHARACTERDATA interface, or using Nodevalue attributes inherited by the XMLNode interface, you can access the content of the annotation. (That is, text between <!-and->). Various methods inherited by the XMLCHARACTERDATA interface can operate the annotation. 

 Use xmldocument.createComment () to create an annotation object.*/
interface XmlComment : XmlCharacterData
{
};
