/*! @Brief XMLCDATASECTION 

 The XMLCDATASECTION interface is a sub -interface of the XMLTEXT interface, which does not define any attributes and methods. By inheriting the NodeValue attribute from the XMLNode interface, or by inheriting the data attribute from the XMLCHARACTERDATA interface, the text content of the CDATA Section can be accessed. 

 Although the XMLCDATASECTION node can usually be treated as the XMLTEXT node, it should be noted that the Normalize method of XMLNode is not incorporated into the adjacent CDATA part. 

 Use the CreatexmlcDataSection method of XMLDOCUMENT to create a XMLCDATASECTION. 

 The CDATA segment contains texts that are not parsed by parsers. The labels in the CDATA section will not be regarded as marking, and the entity will not be unfolded. The main purpose is to contain materials such as XML fragments, without the need for all separators. 

 In a CDATA, the only identified separator is "]>", which can marked the end of the CDATA segment. The CDATA section cannot be nested.*/
interface XmlCDATASection : XmlText
{
};
