/*! @Brief XMLDOCUMENTYPE objects used to access the entity defined by XML*/
interface XmlDocumentType : XmlNode
{
    /*! @brief Return to the name of DTD*/
    readonly String name;

    /*! @brief can return to the external DTD public recognition symbol*/
    readonly String publicId;

    /*! @brief can return to the external DTD system recognition symbol*/
    readonly String systemId;
};
