/*! @Brief XMLNODELIST object represents a sequential node list*/
interface XmlNodeList : object
{
    /*! @Brief Return to the number of nodes in the list of nodes*/
    readonly Integer length;

    /*! @Brief Return to the node of the specified index number in the list of nodes 
      @Param Index Specify the index to be queried 
      @Return Specify the node of the index number*/
    XmlNode item(Integer index);

    /*! @brief can be used to access the data directly with a subscriber*/
    readonly XmlNode operator[];
};
