/*! @Brief XMLNAMEDNODEMAP objects indicate a list of no orderless attributes*/
interface XmlNamedNodeMap : object
{
    /*! @Brief Return to the number of attributes in the list of attribute lists*/
    readonly Integer length;

    /*! @Brief Return to the attribute of the specified index number in the list of attribute lists 
      @Param Index Specify the index to be queried 
      @Return Specify the attribute of the index section*/
    XmlAttr item(Integer index);

    /*! @brief can be used to access the data directly with a subscriber*/
    readonly XmlAttr operator[];

    /*! @brief query the attribute of specified name 
      @param name Specify the name to be query 
      @Return Return to query attributes*/
    XmlAttr getNamedItem(String name);
};
