/*! @Brief XMLPROCESSINGINSTRUCTION object indicates the XML processing instruction*/
interface XmlProcessingInstruction : XmlNode
{
    /*! @brief Return to the goal of the instructions here*/
    readonly String target;

    /*! @brief settings or returned to the content of the instruction here*/
    String data;
};
