/*! @brief xmltext object represents the text content of the element or attribute 

 The XMLTEXT node represents a series of pure text in the XML document. Because pure text appears in the elements and attributes of XML, the XMLTEXT node is usually used as a sub -node of the XMLEMENT node and the XMLATTR node. 

 The XMLTEXT node inherits the XMLCHARACTERDATA interface. It can access the text content of the XMLTEXT node by the Data attribute inherited from the XMLCHARACTERDATA interface or the Nadevalue attribute inherited from the XMLNode interface. 

 The method of the SplitText () method defined by the XMLTEXT interface by the XMLTEXT interface can operate the XMLTEXT node. Create a new XMLTEXT node with XMLDOCUMENT's CreateTextNode. 

 XMLTEXT nodes have no sub -nodes. 

 Regarding the method of deleting the empty XMLTEXT node and the adjacent XMLTEXT node from the sub -tree of the document, see the xmlnode.normalize method.*/
interface XmlText : XmlCharacterData
{
    /*! @Brief divides the text node into two nodes according to the specified offset 

      This method divides the XMLTEXT node into two nodes at the specified Officet. The original XMLTEXT node will be modified so that it contains the text content (but excluding text content) before the position specified by Office. The new XMLTEXT node will be created to store all characters from the OFFSET position (including characters in the position) to the end of the original character. The new XMLTEXT node is the return value of this method. In addition, if the original XMLTEXT node has Parentnode, the new XMLTEXT node will insert this parent node and close to the original node. 

      The XMLCDATASECTION interface inherits the XMLTEXT interface. The XMLCDATASECTION node can also use this method, but the newly created node is the XMLCDATASEAN node, not the XMLTExt node. 
      @Param Offset specifies where to divide text nodes. Start value start with 0 
      @Return divided from the current node, the Text node*/
    XmlText splitText(Integer offset);
};
