/*! @Brief ZIP format File compressed decompression module 

  Instructions: 
  `` `Javascript 
  var zip = request ('zip'); 
  `` `*/
module zip
{
    /*! @brief compressed type constant, not compressed, only store*/
    const ZIP_STORED = 0;

    /*! @Brief compressed type constant, you need to rely on the ZLIB library for compression*/
    const ZIP_DEFLATED = 1;

    /*! @Brief determine whether the file is ZIP format 
 @param Filename file name 
 @Return Return the True representative file is ZIP file*/
    static Boolean isZipFile(String filename) async;

    /*! @Brief open a zip file 
 @Param Path file path 
 @Param mod open the file mode, "R" represents read, "w" is created, "A" represents the addition after the zip file 
 @param compress_type compression type, zip_stored means that it does not compress and only stores. The default uses ZIP_DEFLOTED to use the ZLIB library to compress. 
 @Return Return to ZIP file object*/
    static ZipFile open(String path, String mod = "r", Integer compress_type = ZIP_DEFLATED) async;

    /*! @Brief open a zip file 
 @param data zip file data 
 @Param mod open the file mode, "R" represents read, "w" is created, "A" represents the addition after the zip file 
 @param compress_type compression type, zip_stored means that it does not compress and only stores. The default uses ZIP_DEFLOTED to use the ZLIB library to compress. 
 @Return Return to ZIP file object*/
    static ZipFile open(Buffer data, String mod = "r", Integer compress_type = ZIP_DEFLATED) async;

    /*! @Brief open a zip file 
 @param Strm Zip file stream 
 @Param mod open the file mode, "R" represents read, "w" is created, "A" represents the addition after the zip file 
 @param compress_type compression type, zip_stored means that it does not compress and only stores. The default uses ZIP_DEFLOTED to use the ZLIB library to compress. 
 @Return Return to ZIP file object*/
    static ZipFile open(SeekableStream strm, String mod = "r", Integer compress_type = ZIP_DEFLATED) async;
};
