on:
    push:
        branches:    
          - master
          - dev
          - ci
          - 'feat/*'
        # Sequence of patterns matched against refs/tags
        tags:        
          - v*
jobs:
    windows:
        strategy:
            matrix:
                Platform: [x86, x64]
        name: ${{ matrix.Platform }} build
        runs-on: windows-latest
        env:
            PLATFORM: ${{ matrix.Platform }}
            GithubAction: true
        steps:
            - uses: actions/checkout@v1
            - uses: olegtarasov/get-tag@v1-release
              id: tagName
            - name: Initialize Submodules
              run: |
                git submodule init
                git submodule update
              shell: cmd
            - name: Setup MSBuild.exe
              uses: warrenbuckley/Setup-MSBuild@v1
            - name: Just Build
              run: |
                IF /I "%PLATFORM%" == "x64" ECHO "x64 building..." && build release amd64 && cd test && ..\bin\Windows_amd64_release\fibjs.exe --prof main.js
                IF /I "%PLATFORM%" == "x86" ECHO "x86 building..." && build release i386 && cd test && ..\bin\Windows_i386_release\fibjs.exe --prof main.js
                SET GA_TAG=${{ steps.tagName.outputs.tag }}
                IF /I "%GA_TAG%" == "" set GA_TAG=dist
                mkdir %GA_TAG%
                IF /I "%PLATFORM%" == "x64" copy .\bin\Windows_amd64_release\fibjs.exe .\%GA_TAG%\fibjs-%GA_TAG%-windows-x64.exe
                IF /I "%PLATFORM%" == "x64" copy .\bin\Windows_amd64_release\fibjs_gui.exe .\%GA_TAG%\fibjs-%GA_TAG%-windows-gui-x64.exe
                IF /I "%PLATFORM%" == "x64" copy .\bin\Windows_amd64_release\installer.exe .\%GA_TAG%\installer-%GA_TAG%-windows-x64.exe
                IF /I "%PLATFORM%" == "x64" copy .\bin\Windows_amd64_release\fibjs.cab .\%GA_TAG%\fibjs-%GA_TAG%-windows-x64.cab
                IF /I "%PLATFORM%" == "x86" copy .\bin\Windows_i386_release\fibjs.exe .\%GA_TAG%\fibjs-%GA_TAG%-windows-x86.exe
                IF /I "%PLATFORM%" == "x86" copy .\bin\Windows_i386_release\fibjs_gui.exe .\%GA_TAG%\fibjs-%GA_TAG%-windows-gui-x86.exe
                IF /I "%PLATFORM%" == "x86" copy .\bin\Windows_i386_release\installer.exe .\%GA_TAG%\installer-%GA_TAG%-windows-x86.exe
                IF /I "%PLATFORM%" == "x86" copy .\bin\Windows_i386_release\fibjs.cab .\%GA_TAG%\fibjs-%GA_TAG%-windows-x86.cab
              shell: cmd
            - name: Generate the artifacts
              uses: skx/github-action-build@master
            - name: Upload the artifacts
              uses: skx/github-action-publish-binaries@master
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                args: '.\GA_TAG\*.exe'